export const formConfigs = [
  {
    id: 0,
    title: "전기 CO₂ 발생량",
    inputTitle: "전기 사용량",
    units: "kwh",
    calcNum: 0.4781,
    keyword: "전기",
  },
  {
    id: 1,
    title: "가스 CO₂ 발생량",
    inputTitle: "가스 사용량",
    units: "m³",
    calcNum: 2.176,
    keyword: "가스",
  },
  {
    id: 2,
    title: "수도 CO₂ 발생량",
    inputTitle: "수도 사용량",
    units: "m³",
    calcNum: 0.237,
    keyword: "수도",
  },
  {
    id: 3,
    title: "교통 CO₂ 발생량",
    inputTitle: "교통 사용량",
    units: "km",
    types: ["휘발유", "경유", "LPG", "승용차 없음"],
    calcNum: 2.097,
    keyword: "교통",
  },
  {
    id: 4,
    title: "생활 폐기물 CO₂ 발생량",
    inputTitle: "폐기물 배출량",
    units: "kg",
    types: ["kg", "L"],
    calcNum: 0.5573,
    keyword: "폐기물",
  },
];
